/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.2.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Fixture { 
    fixture_id?: number;
    referee?: string;
    home_team_id?: number;
    away_team_id?: number;
    home_goals?: number;
    away_goals?: number;
    league_id?: number;
    season_year?: number;
    round?: string;
    date?: number;
}