/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.2.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TeamStanding { 
    team_id?: number;
    rank?: number;
    team_name?: string;
    team_logo?: string;
    points?: number;
    goals_diff?: string;
    form?: string;
    description?: string;
}